### PR TITLE
fix(Typos in artifacts #70): Update Artifact Names 

### PR DESCRIPTION
**Pull request by Deadmano**
Updated some artifact names to reflect their in-game name and made quotes consistent.

### CODE REVIEW

**Comment by Deadmano** [comment]
#69 insert obligatory `le giggle` here.

**Comment by DasithKuruppu** [comment]
On the commit message could you update it to reflect the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) format ? 

i.e

`fix(Typos in artifacts #70): something something..`

**Comment by Deadmano** [comment]
@DasithKuruppu happy to see more adopt conventional commits! This should be good to merge?

**Comment by DasithKuruppu** [comment]
> @DasithKuruppu happy to see more adopt conventional commits! This should be good to merge?

Merged it. Appreciate it !

**Pull request merged**
